"""Initial migration

Revision ID: 0af52691dad3
Revises: 
Create Date: 2024-10-23 12:40:59.765685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af52691dad3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('breeds_breed_name_key', 'breeds', type_='unique')
    op.create_unique_constraint(op.f('uq_breeds_breed_name'), 'breeds', ['breed_name'])
    op.drop_constraint('followers_follower_pet_id_followed_pet_id_key', 'followers', type_='unique')
    op.alter_column('friendships', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('friendships_pet_id_1_pet_id_2_key', 'friendships', type_='unique')
    op.alter_column('group_members', 'admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('groups', 'privacy',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('pet_types_type_name_key', 'pet_types', type_='unique')
    op.create_unique_constraint(op.f('uq_pet_types_type_name'), 'pet_types', ['type_name'])
    op.alter_column('pets', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('private_messages', 'read_status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('reports', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('roles_role_name_key', 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_role_name'), 'roles', ['role_name'])
    op.drop_constraint('user_roles_user_id_role_id_key', 'user_roles', type_='unique')
    op.alter_column('users', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('users_user_email_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_user_email'), 'users', ['user_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_user_email'), 'users', type_='unique')
    op.create_unique_constraint('users_user_email_key', 'users', ['user_email'])
    op.alter_column('users', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.create_unique_constraint('user_roles_user_id_role_id_key', 'user_roles', ['user_id', 'role_id'])
    op.drop_constraint(op.f('uq_roles_role_name'), 'roles', type_='unique')
    op.create_unique_constraint('roles_role_name_key', 'roles', ['role_name'])
    op.alter_column('reports', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('private_messages', 'read_status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('pets', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_pet_types_type_name'), 'pet_types', type_='unique')
    op.create_unique_constraint('pet_types_type_name_key', 'pet_types', ['type_name'])
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('groups', 'privacy',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('group_members', 'admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_unique_constraint('friendships_pet_id_1_pet_id_2_key', 'friendships', ['pet_id_1', 'pet_id_2'])
    op.alter_column('friendships', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.create_unique_constraint('followers_follower_pet_id_followed_pet_id_key', 'followers', ['follower_pet_id', 'followed_pet_id'])
    op.drop_constraint(op.f('uq_breeds_breed_name'), 'breeds', type_='unique')
    op.create_unique_constraint('breeds_breed_name_key', 'breeds', ['breed_name'])
    # ### end Alembic commands ###
