# Web Framework y Servidor
fastapi==0.104.1
uvicorn[standard]==0.24.0

# Base de datos y ORM
sqlalchemy==2.0.23
alembic==1.12.1
psycopg2-binary==2.9.9

# Autenticaci贸n y Seguridad
python-jose[cryptography]==3.3.0
passlib[bcrypt]==1.7.4
python-multipart==0.0.6

# Configuraci贸n y Validaci贸n
python-dotenv==1.0.0
pydantic==2.9.2
pydantic-settings==2.6.0
email-validator==2.1.0

# Cache y Almacenamiento
redis==5.0.1
boto3==1.29.3
Pillow==11.0.0

# Procesamiento y Utilidades
python-magic==0.4.27
aiofiles==24.1.0
requests==2.31.0

# Monitoreo y Logging
prometheus-client==0.19.0
sentry-sdk[fastapi]==1.35.0

# Testing
pytest==7.4.3
httpx==0.25.1

# Dependencias de producci贸n
gunicorn==21.2.0